export const menu = [
  { name: 'Calendários', link: '#' },
  {
    id: 2,
    name: 'Resultados',
    link: 'https://seqm.com.br/resultados',
    parent_id: null,
    open_submenu: false,
    sub_menu: [],
  },
  {
    id: 3,
    name: 'Ranking',
    link: '#',
    parent_id: null,
    open_submenu: false,
    sub_menu: [
      {
        id: 0,
        name: 'Geral',
        link: 'https://seqm.com.br/ranking/geral',
        parent_id: 3,
        open_submenu: false,
        sub_menu: null,
      },
      {
        id: 0,
        name: 'Competidor',
        link: '#',
        parent_id: 3,
        open_submenu: false,
        sub_menu: null,
      },
      {
        id: 0,
        name: 'Animal',
        link: '#',
        parent_id: 3,
        open_submenu: false,
        sub_menu: null,
      },
      {
        id: 0,
        name: 'Reprodutor',
        link: '#',
        parent_id: 3,
        open_submenu: false,
        sub_menu: null,
      },
      {
        id: 0,
        name: 'Reprodutora',
        link: '#',
        parent_id: 3,
        open_submenu: false,
        sub_menu: null,
      },
      {
        id: 0,
        name: 'Avô',
        link: '#',
        parent_id: 3,
        open_submenu: false,
        sub_menu: null,
      },
      {
        id: 0,
        name: 'Proprietário',
        link: '#',
        parent_id: 3,
        open_submenu: false,
        sub_menu: null,
      },
      {
        id: 0,
        name: 'Criador',
        link: '#',
        parent_id: 3,
        open_submenu: false,
        sub_menu: null,
      },
      {
        id: 0,
        name: 'Premiação',
        link: '#',
        parent_id: 3,
        open_submenu: false,
        sub_menu: null,
      },
    ],
  },
  {
    id: 4,
    name: 'Campeonatos',
    link: '#',
    parent_id: null,
    open_submenu: false,
    sub_menu: [],
  },
  {
    id: 5,
    name: 'Eventos',
    link: '#',
    parent_id: null,
    open_submenu: false,
    sub_menu: [
      {
        id: 0,
        name: 'Eventos Oficializados',
        link: '#',
        parent_id: 5,
        open_submenu: false,
        sub_menu: null,
      },
      {
        id: 0,
        name: 'Meus Calendarios',
        link: '#',
        parent_id: 5,
        open_submenu: false,
        sub_menu: null,
      },
      {
        id: 0,
        name: 'Participações',
        link: '#',
        parent_id: 5,
        open_submenu: false,
        sub_menu: null,
      },
    ],
  },
  {
    id: 6,
    name: 'Premiações',
    link: '#',
    parent_id: null,
    open_submenu: false,
    sub_menu: [],
  },
  {
    id: 7,
    name: 'Awards',
    link: '#',
    parent_id: null,
    open_submenu: false,
    sub_menu: [],
  },
  {
    id: 8,
    name: 'Financeiro',
    link: '#',
    parent_id: null,
    open_submenu: false,
    sub_menu: [],
  },
  {
    id: 9,
    name: 'Acesso restrito',
    link: '#',
    parent_id: null,
    open_submenu: false,
    sub_menu: [],
  },
];
