import { MenuType } from '@abqm-ds/react';

export const menu: MenuType = [
  {
    id: 1,
    name: 'Calendários',
    link: 'https://react-seqm-calendario-qas.seqm.com.br/',
    parent_id: null,
    open_submenu: false,
    need_login: false,
    link_login: null,
    sub_menu: [],
    path: null,
  },
  {
    id: 2,
    name: 'Resultados',
    link: 'https://react-seqm-resultados-qas.seqm.com.br/',
    parent_id: null,
    open_submenu: false,
    need_login: false,
    link_login: null,
    sub_menu: [],
    path: null,
  },
  {
    id: 3,
    name: 'Ranking',
    link: '#',
    parent_id: null,
    open_submenu: false,
    need_login: true,
    link_login: 'https://react-seqm-login-qas.seqm.com.br',
    sub_menu: [
      {
        id: 0,
        name: 'Geral',
        link: 'https://react-seqm-ranking-qas.seqm.com.br/geral',
        parent_id: 3,
        open_submenu: false,
        need_login: true,
        link_login: 'https://react-seqm-login-qas.seqm.com.br',
        sub_menu: null,
        path: '/ranking/geral',
      },
      {
        id: 0,
        name: 'Competidor',
        link: 'https://react-seqm-ranking-qas.seqm.com.br/competidor',
        parent_id: 3,
        open_submenu: false,
        need_login: true,
        link_login: 'https://react-seqm-login-qas.seqm.com.br',
        sub_menu: null,
        path: null,
      },
      {
        id: 0,
        name: 'Animal',
        link: 'https://react-seqm-ranking-qas.seqm.com.br/animal',
        parent_id: 3,
        open_submenu: false,
        need_login: true,
        link_login: 'https://react-seqm-login-qas.seqm.com.br',
        sub_menu: null,
        path: null,
      },
      {
        id: 0,
        name: 'Reprodutor',
        link: 'https://react-seqm-ranking-qas.seqm.com.br/reprodutor',
        parent_id: 3,
        open_submenu: false,
        need_login: true,
        link_login: 'https://react-seqm-login-qas.seqm.com.br',
        sub_menu: null,
        path: null,
      },
      {
        id: 0,
        name: 'Reprodutora',
        link: 'https://react-seqm-ranking-qas.seqm.com.br/reprodutora',
        parent_id: 3,
        open_submenu: false,
        need_login: true,
        link_login: 'https://react-seqm-login-qas.seqm.com.br',
        sub_menu: null,
        path: null,
      },
      {
        id: 0,
        name: 'Avô',
        link: 'https://react-seqm-ranking-qas.seqm.com.br/avo',
        parent_id: 3,
        open_submenu: false,
        need_login: true,
        link_login: 'https://react-seqm-login-qas.seqm.com.br',
        sub_menu: null,
        path: null,
      },
      {
        id: 0,
        name: 'Proprietário',
        link: 'https://react-seqm-ranking-qas.seqm.com.br/proprietario',
        parent_id: 3,
        open_submenu: false,
        need_login: true,
        link_login: 'https://react-seqm-login-qas.seqm.com.br',
        sub_menu: null,
        path: null,
      },
      {
        id: 0,
        name: 'Criador',
        link: 'https://react-seqm-ranking-qas.seqm.com.br/criador',
        parent_id: 3,
        open_submenu: false,
        need_login: true,
        link_login: 'https://react-seqm-login-qas.seqm.com.br',
        sub_menu: null,
        path: null,
      },
      {
        id: 0,
        name: 'Premiação',
        link: 'https://react-seqm-ranking-qas.seqm.com.br/premiacao',
        parent_id: 3,
        open_submenu: false,
        need_login: true,
        link_login: 'https://react-seqm-login-qas.seqm.com.br',
        sub_menu: null,
        path: null,
      },
    ],
    path: null,
  },
  {
    id: 4,
    name: 'Campeonatos',
    link: '#',
    parent_id: null,
    open_submenu: false,
    need_login: false,
    link_login: null,
    sub_menu: [],
    path: null,
  },
  {
    id: 5,
    name: 'Eventos',
    link: '#',
    parent_id: null,
    open_submenu: false,
    need_login: true,
    link_login: 'https://react-seqm-login-qas.seqm.com.br',
    sub_menu: [
      {
        id: 0,
        name: 'Eventos Oficializados',
        link: '#',
        parent_id: 5,
        open_submenu: false,
        need_login: false,
        link_login: null,
        sub_menu: null,
        path: null,
      },
      {
        id: 0,
        name: 'Meus Calendarios',
        link: '#',
        parent_id: 5,
        open_submenu: false,
        need_login: false,
        link_login: null,
        sub_menu: null,
        path: null,
      },
      {
        id: 0,
        name: 'Participações',
        link: '#',
        parent_id: 5,
        open_submenu: false,
        need_login: false,
        link_login: null,
        sub_menu: null,
        path: null,
      },
    ],
    path: null,
  },
  {
    id: 6,
    name: 'Premiações',
    link: '#',
    parent_id: null,
    open_submenu: false,
    need_login: false,
    link_login: null,
    sub_menu: [],
    path: null,
  },
  {
    id: 7,
    name: 'Awards',
    link: '#',
    parent_id: null,
    open_submenu: false,
    need_login: false,
    link_login: null,
    sub_menu: [],
    path: null,
  },
  {
    id: 8,
    name: 'Financeiro',
    link: '#',
    parent_id: null,
    open_submenu: false,
    need_login: true,
    link_login: 'https://react-seqm-login-qas.seqm.com.br',
    sub_menu: [],
    path: null,
  },
  {
    id: 9,
    name: 'Acesso restrito',
    link: '#',
    parent_id: null,
    open_submenu: false,
    need_login: false,
    link_login: null,
    sub_menu: [],
    path: null,
  },
];
