# Workflow name
name: Build and Publish Storybook to GitHub Pages

on:
  # Event for the workflow to run on
  push:
    branches:
      - "main" # Replace with the branch you want to deploy from

permissions:
  contents: read
  pages: write
  id-token: write

# List of jobs
jobs:
  deploy:
    runs-on: ubuntu-latest
    # Job steps
    steps:
      # Manual Checkout
      - name: "Manual Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Set up Node
      - name: "Setup Node"
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      #👇 Add Storybook build and deploy to GitHub Pages as a step in the workflow
      - name: "Storybook Deploy to GitHub Pages"
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        env:
          TURBO_TOKEN: VFu4dcZ5FhMP2Dg2b8R14LNt
          TURBO_TEAM: jorgewsantos-projects
        with:
          install_command: npm install # default: npm ci
          build_command: npm run build # default: npm run build-storybook
          path: ./packages/docs/storybook-static # default: dist/storybook
          checkout: false # default: true

