name: Release | Publicação no NPM

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      # Manual Checkout
      - name: 'Manual Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Set up Node
      - name: 'Setup Node'
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: NPM Install
        run: npm i

      - name: Set up Git credentials
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN_CUSTOM }}@github.com/${{ github.repository }}

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_CUSTOM }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          TURBO_TOKEN: ${{ secrets.VERCEL_CACHE_TOKEN }}
          TURBO_TEAM: jorgewsantos-projects
